# Generated by Django 4.2.7 on 2023-11-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_postmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='context',
            new_name='content',
        ),
    ]
